In [1]:
import pandas as pd
base = pd.read_csv('house-prices.csv')
base.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [2]:
base.shape

(21613, 21)

In [3]:
X = base.iloc[:, 5:6].values
y = base.iloc[:, 2:3].values

In [4]:
X

array([[1180],
       [2570],
       [ 770],
       ...,
       [1020],
       [1600],
       [1020]], dtype=int64)

In [5]:
y

array([[221900.],
       [538000.],
       [180000.],
       ...,
       [402101.],
       [400000.],
       [325000.]])

In [6]:
from sklearn.preprocessing import StandardScaler
scaler_x = StandardScaler()
X = scaler_x.fit_transform(X)
scaler_y = StandardScaler()
y = scaler_y.fit_transform(y)

In [7]:
X

array([[-0.97983502],
       [ 0.53363434],
       [-1.42625404],
       ...,
       [-1.15404732],
       [-0.52252773],
       [-1.15404732]])

In [8]:
y

array([[-0.86671733],
       [-0.00568792],
       [-0.98084935],
       ...,
       [-0.37586519],
       [-0.38158814],
       [-0.58588173]])

In [9]:
import tensorflow as tf

In [10]:
colunas = [tf.feature_column.numeric_column('x', shape = [1])]

In [11]:
colunas

[NumericColumn(key='x', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)]

In [12]:
regressor = tf.estimator.LinearRegressor(feature_columns=colunas)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'C:\\Users\\thale\\AppData\\Local\\Temp\\tmp7bdd16jf', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000001E02594C3C8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [13]:
from sklearn.model_selection import train_test_split
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size = 0.3)

In [14]:
X_treinamento.shape

(15129, 1)

In [15]:
y_treinamento.shape

(15129, 1)

In [16]:
X_teste.shape

(6484, 1)

In [17]:
y_teste.shape

(6484, 1)

In [18]:
funcao_treinamento = tf.estimator.inputs.numpy_input_fn({'x': X_treinamento}, y_treinamento,
                                                        batch_size = 32, num_epochs = None, 
                                                        shuffle = True)

In [19]:
funcao_teste = tf.estimator.inputs.numpy_input_fn({'x': X_teste}, y_teste, batch_size = 32, 
                                                  num_epochs = 1000, shuffle = False)

In [20]:
regressor.train(input_fn = funcao_treinamento, steps = 10000)

Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling model_fn.
Instructions for updating:
Use `tf.cast` instead.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Saving checkpoints for 0 into C:\Users\thale\AppData\Local\Temp\tmp7bdd16jf\model.ckpt.
INFO:tensorflow:loss = 62.5965, step = 1
INFO:tensorflow:global_step/sec: 1000.02
INFO:tensorflow:loss = 16.333675,

INFO:tensorflow:global_step/sec: 1587.3
INFO:tensorflow:loss = 9.391718, step = 5601 (0.063 sec)
INFO:tensorflow:global_step/sec: 1315.78
INFO:tensorflow:loss = 6.0163784, step = 5701 (0.076 sec)
INFO:tensorflow:global_step/sec: 1428.58
INFO:tensorflow:loss = 6.3382797, step = 5801 (0.071 sec)
INFO:tensorflow:global_step/sec: 1666.67
INFO:tensorflow:loss = 7.806306, step = 5901 (0.060 sec)
INFO:tensorflow:global_step/sec: 1612.85
INFO:tensorflow:loss = 10.3153, step = 6001 (0.061 sec)
INFO:tensorflow:global_step/sec: 1694.99
INFO:tensorflow:loss = 15.706558, step = 6101 (0.060 sec)
INFO:tensorflow:global_step/sec: 1666.62
INFO:tensorflow:loss = 7.0925355, step = 6201 (0.059 sec)
INFO:tensorflow:global_step/sec: 1694.94
INFO:tensorflow:loss = 14.514145, step = 6301 (0.060 sec)
INFO:tensorflow:global_step/sec: 1666.66
INFO:tensorflow:loss = 10.494802, step = 6401 (0.059 sec)
INFO:tensorflow:global_step/sec: 1666.69
INFO:tensorflow:loss = 38.61815, step = 6501 (0.061 sec)
INFO:tensorflow:

In [21]:
metricas_treinamento = regressor.evaluate(input_fn = funcao_treinamento, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2020-01-11T15:35:07Z
INFO:tensorflow:Graph was finalized.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from C:\Users\thale\AppData\Local\Temp\tmp7bdd16jf\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2020-01-11-15:35:13
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.50582683, global_step = 100

In [22]:
metricas_teste = regressor.evaluate(input_fn = funcao_teste, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2020-01-11T15:35:14Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\thale\AppData\Local\Temp\tmp7bdd16jf\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2020-01-11-15:35:19
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.5099522, global_step = 10000, label/mean = 0.0014611839, loss = 16.31847, prediction/mean = 0.007677458
INFO:tenso

In [23]:
metricas_treinamento

{'average_loss': 0.50582683,
 'label/mean': -0.0006181499,
 'loss': 16.186459,
 'prediction/mean': -0.0005127219,
 'global_step': 10000}

In [24]:
metricas_teste

{'average_loss': 0.5099522,
 'label/mean': 0.0014611839,
 'loss': 16.31847,
 'prediction/mean': 0.007677458,
 'global_step': 10000}

In [25]:
import numpy as np
novas_casas = np.array([[800], [900], [1000]])
novas_casas

array([[ 800],
       [ 900],
       [1000]])

In [26]:
novas_casas = scaler_x.transform(novas_casas)
novas_casas

array([[-1.39358923],
       [-1.28470655],
       [-1.17582386]])

In [27]:
funcao_previsao = tf.estimator.inputs.numpy_input_fn({'x': novas_casas}, shuffle = False)

In [28]:
previsoes = regressor.predict(input_fn = funcao_previsao)

In [29]:
previsoes

<generator object Estimator.predict at 0x000001E0259519C8>

In [30]:
list(previsoes)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\thale\AppData\Local\Temp\tmp7bdd16jf\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


[{'predictions': array([-0.9831038], dtype=float32)},
 {'predictions': array([-0.906138], dtype=float32)},
 {'predictions': array([-0.82917213], dtype=float32)}]

In [31]:
for p in regressor.predict(input_fn = funcao_previsao):
    #print(p['predictions'])
    print(scaler_y.inverse_transform(p['predictions']))

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\thale\AppData\Local\Temp\tmp7bdd16jf\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
[179172.36]
[207427.92]
[235683.55]
