In [1]:
import tensorflow as tf

In [2]:
p = tf.placeholder('float', None)

In [3]:
action = p + 2

In [4]:
with tf.Session() as sess:
    #sess.run(action)
    result = sess.run(action, feed_dict = {p: [1,2,3]})
    print(result)

[3. 4. 5.]


In [5]:
p2 = tf.placeholder('float',[None, 5])
action2 = p2 * 5

In [7]:
with tf.Session() as sess:
    data = [[1,2,3,4,5],[6,7,8,9,10]]
    result = sess.run(action2, feed_dict = {p2: data})
    print(result)

[[ 5. 10. 15. 20. 25.]
 [30. 35. 40. 45. 50.]]
