In [1]:
import tensorflow as tf

In [2]:
a = tf.constant([9,8,7], name = "a")
b = tf.constant([1,2,3], name = "b")

In [3]:
sum = a + b

In [4]:
print(sum)

Tensor("add:0", shape=(3,), dtype=int32)


In [8]:
with tf.Session() as sess:
    print(sess.run(sum))

[10 10 10]


In [10]:
a1 = tf.constant([[1,2,3],[4,5,6]], name = "a1")

In [11]:
print(a1)

Tensor("Const:0", shape=(2, 3), dtype=int32)


In [12]:
a1.shape

TensorShape([Dimension(2), Dimension(3)])

In [13]:
b1 = tf.constant([[1,2,3],[4,5,6]], name = "b1")

In [14]:
sum1 = tf.add(a1,b1)

In [15]:
print(sum1)

Tensor("Add_1:0", shape=(2, 3), dtype=int32)


In [20]:
with tf.Session() as sess:
    print(sess.run(a1))
    print(sess.run(b1))
    print(sess.run(sum1))

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]


In [22]:
a2 = tf.constant([[1,2,3], [4,5,6]])
b2 = tf.constant([[1],[2]])
sum2 = tf.add(a2,b2)

In [24]:
with tf.Session() as sess:
    print(sess.run(a2))
    print(sess.run(b2))
    print(sess.run(sum2))

[[1 2 3]
 [4 5 6]]
[[1]
 [2]]
[[2 3 4]
 [6 7 8]]
